#!/usr/bin/env python
import serial
import rospy
from std_msgs.msg import Float32
from std_msgs.msg import Float64
from std_msgs.msg import String
import smbus
import time
bus=smbus.SMBus(1)#i2c read from dianweiqi
def talker():
    pub_wind=rospy.Publisher("wind_direction_apparent",Float64,queue_size=10)
    rospy.init_node('wind_direction_apparent', anonymous=True)
    while not rospy.is_shutdown():
        wind_direction_apparent=bus.read_byte_data(0x48,0x40)/255.0*360.0
        pub_wind.publish(wind_direction_apparent)
        rate.sleep()

if __name__ == '__main__':
    try:
        talker()
    except rospy.ROSInterruptException:
        pass