# Sail position settings for sail sets 2 and 3 (medium & smaller sails)

# format: wind angle (as read from wind sensor), wind speed (m/s), scaled servo PWM
# scaled servo PWM: 0 = sail fully sheeted in, min PWM; 1 = sail fully out, max PWM
# linearly scaled inbetween
# CAUTION: include 0 angle and 180 angle, since those are the initial values in the lookup script

# sailsettings/table: {'0': 0,
#                     '36': 0,
#                     '40': 0.0519,
#                     '53': 0.0889,
#                     '85': 0.2222,
#                     '105': 0.4444,
#                     '160': 0.7555,
#                     '178': 1,
#                     '180': 1,
#                     }

sailsettings/table: {'0': 0,
                     '17': 0.1667,
                     '46': 0.3333,
                     '80': 0.5,
                     '110': 0.6667,
                     '140': 0.8333,
                     '165': 1,
                     '180': 1,
                      }

#sailsettings/table: {'0': 1500,
 #                    '17': 1600,
  #                   '46': 1700,
  #                   '80': 1800,
   #                  '110': 1900,
    #                 '140': 2000,
     #                '180': 2100,
      #               
       #              
   #                  }

# Servo PWM limits in microseconds
sail/servolowerlimits: 1500
sail/servohigherlimits: 2100
sail/PWMoffset: 0

sailsettings/windSpeed: 2
