# Sail position settings for sail sets 2 and 3 (medium & smaller sails)

# format: wind angle (as read from wind sensor), wind speed (m/s), scaled servo PWM
# scaled servo PWM: 0 = sail fully sheeted in, min PWM; 1 = sail fully out, max PWM
# linearly scaled inbetween
# CAUTION: include 0 angle and 180 angle, since those are the initial values in the lookup script

# sailsettings/table: {'0': 0,
#                     '36': 0,
#                     '40': 0.0519,
#                     '53': 0.0889,
#                     '85': 0.2222,
#                     '105': 0.4444,
#                     '160': 0.7555,
#                     '178': 1,
#                     '180': 1,
#                     }
# sailsettings/table: {'0 ': 2070,
#                     '33.38': 1950
#                     '53.14': 1850,
#                     '77.3': 1750,
#                     '90': 1650,
#                     '115.98': 1550,
#                     '123.8': 1450,
#                     '180': 1450,
                    
                    
#                     }

sailsettings/table: {'0 ': 1,
                    '33': 0.806,
                    '53': 0.645,
                    '77': 0.483,
                    '90': 0.322,
                    '116': 0.161,
                    '124': 0.052,
                    '180': 0,
                    
                    
                    }

# Servo PWM limits in microseconds
sail/servolowerlimits: 1450
sail/servohigherlimits: 2070
sail/PWMoffset: 0

sailsettings/windSpeed: 2
