#!/usr/bin/env python
"""Node steps through a series of tasks to perform.

Tasks (or waypoints) are loaded from parameters, and then each one is used to
calculate sailing_state and goal_heading until its check_end_condition()
returns True.
"""

import rospy
import time
from std_msgs.msg import Float32
from std_msgs.msg import Float64
from std_msgs.msg import Int16
from std_msgs.msg import String
from dynamic_reconfigure.server import Server
import sailing_robot
from sailing_robot.tasks import tasks_from_wps
from sailing_robot.tasks_ros import RosTasksRunner
from sailing_robot.navigation import Navigation
from sailing_robot.cfg import TackVotingConfig
from sensor_msgs.msg import NavSatFix

chunyu = -1

def goal_heading_publisher(tasks_runner,task):
    pub = rospy.Publisher("goal_heading", Float32, queue_size=10)
    pub_state = rospy.Publisher("sailing_state", String, queue_size=10)
    # pub_tack = r
    rate = rospy.Rate(rospy.get_param("config/rate"))

    tasks_runner.start_next_task(task)

    while not rospy.is_shutdown():
        state, goal_heading = tasks_runner.calculate_state_and_goal()
        pub.publish(goal_heading)
        pub_state.publish(state)
        rate.sleep()

def jibe_tack_now(msg):
    tasks_runner.insert_task({
        'kind': 'jibe_tack_now',
        'action': msg.data,
    })


def insert_waypoint(msg):
    tasks_runner.insert_task({
        'kind': 'to_waypoint',
        'waypoint_ll': (msg.latitude, msg.longitude),
        'target_radius': 2.5,     # set default value, hot fix for the force jibing node
        'tack_voting_radius': 1 # set default value, hot fix for the force jibing node
    })

def tack_voting_callback(config, level):
    """
    get updates for the dynamic parameters
    """
    radius = config.radius
    samples = config.samples
    threshold = config.threshold
    return config

def continue_last_task(msg):
    global chunyu 
    chunyu = msg.data

if __name__ == '__main__':
    try:
        rospy.init_node("publish_goal_heading", anonymous=True)

        PUB_task_state = rospy.Publisher("task_state", String, queue_size=10)
        rospy.logwarn("out out chunyu = " + str(chunyu))

        rospy.Subscriber('last_task', Int16, continue_last_task)
        time.sleep(1)
        task = chunyu
        rospy.logwarn('task = ' + str(task))
        if task == -1:
            time.sleep(10)
            rospy.logwarn('start our task!')

        #first start sleep for 100s

        else:
            task = task
            rospy.logwarn('start our task again!')
        #did break before

        # rospy.logwarn('begin delay')
        # while True :
        #     time.sleep(100)
        #     break
        # rospy.logwarn('end delay')
        tasks = tasks_from_wps(rospy.get_param("wp") )
        # tasks_2 = tasks_from_wps(rospy.get_param("wp2") )

        nav_options = rospy.get_param("navigation")
        
        nav = Navigation(**nav_options)
        
        tasks_runner = RosTasksRunner(tasks, nav)
        # tasks_runner_2 = RosTasksRunner(tasks_2, nav)


        rospy.Subscriber('heading', Float32, nav.update_heading)
        rospy.Subscriber('wind_direction_apparent', Float64, nav.update_wind_direction)
        rospy.Subscriber('position', NavSatFix, nav.update_position)

        rospy.Subscriber('temporary_wp', NavSatFix, insert_waypoint)
        rospy.Subscriber('jibe_tack_now', String, jibe_tack_now)
        srv = Server(TackVotingConfig, tack_voting_callback)

        PUB_task_state.publish('tasks alive!!')
        goal_heading_publisher(tasks_runner,task)

        
        # goal_heading_publisher(tasks_runner_2)

    except rospy.ROSInterruptException:
        PUB_task_state.publish('tasks died!!')
        pass
